stages:
  - lint
  - test
  - publish

flake8:
  stage: lint
  image: python:3.6
  script:
    - pip install flake8==3.5.0
    - flake8 $(find ./ -name "*.py")

test:
  stage: test
  image: python:3.6
  script:
    - pip install Flask==1.0.2
    - pip install requests==2.18.4
    - pip install nose==1.3.7
    - pip install coverage==4.5.1
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/edmclient
    - nosetests --with-coverage --cover-package=edmclient

publish-github:
  stage: publish
  image: docker:17.07
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  script:
    - apk update && apk add git
    - git push -u https://${GITHUB_USER_NAME}:${GITHUB_USER_TOKEN}@github.com/arbor/fidoclient.git HEAD:master
    - git push -u https://${GITHUB_USER_NAME}:${GITHUB_USER_TOKEN}@github.com/arbor/fidoclient.git ${CI_COMMIT_TAG}

publish-pypi:
  stage: publish
  image: python:3.6-alpine
  variables:
    TWINE_USERNAME: ${PYPI_USERNAME}
    TWINE_PASSWORD: ${PYPI_PASSWORD}
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  before_script:
    - pip install twine
    - sed -i "s/<version#>/${CI_COMMIT_TAG}/g" setup.py
    - python setup.py sdist bdist_wheel
  script:
    - twine upload --repository-url ${PYPI_PROD_URL} dist/*