stages:
  - lint
  - test
  - publish

flake8:
  stage: lint
  image: python:3.6
  script:
    - pip install flake8==3.5.0
    - flake8 $(find ./ -name "*.py")

test:
  stage: test
  image: python:3.6
  script:
    - pip install Flask==1.0.2
    - pip install requests==2.18.4
    - pip install nose==1.3.7
    - pip install coverage==4.5.1
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/edmclient
    - nosetests --with-coverage --cover-package=edmclient

publish-github:
  stage: publish
  image: docker:17.07
  only:
    - tags
  script:
    - apk update && apk add git
    - git config --global user.name "${GITHUB_USER_NAME}"
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - LATEST=$(git describe --tags `git rev-list --tags --max-count=1`)
    - git push -u https://${GITHUB_USER_NAME}:${GITHUB_USER_TOKEN}@github.com/arbor/fidoclient.git master
    - git push -u https://${GITHUB_USER_NAME}:${GITHUB_USER_TOKEN}@github.com/arbor/fidoclient.git ${LATEST}
